// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "api/polyterm-testing.mdx": () => import("../content/docs/api/polyterm-testing.mdx?collection=docs"), "api/polyterm-ui.mdx": () => import("../content/docs/api/polyterm-ui.mdx?collection=docs"), "api/polyterm-web.mdx": () => import("../content/docs/api/polyterm-web.mdx?collection=docs"), "components/ascii.mdx": () => import("../content/docs/components/ascii.mdx?collection=docs"), "components/canvas.mdx": () => import("../content/docs/components/canvas.mdx?collection=docs"), "components/chat.mdx": () => import("../content/docs/components/chat.mdx?collection=docs"), "components/gradient.mdx": () => import("../content/docs/components/gradient.mdx?collection=docs"), "components/link.mdx": () => import("../content/docs/components/link.mdx?collection=docs"), "components/made-with-opentui.mdx": () => import("../content/docs/components/made-with-opentui.mdx?collection=docs"), "components/made-with-polyterm.mdx": () => import("../content/docs/components/made-with-polyterm.mdx?collection=docs"), "components/modal.mdx": () => import("../content/docs/components/modal.mdx?collection=docs"), "components/multi-select.mdx": () => import("../content/docs/components/multi-select.mdx?collection=docs"), "components/primitives.mdx": () => import("../content/docs/components/primitives.mdx?collection=docs"), "components/select-input.mdx": () => import("../content/docs/components/select-input.mdx?collection=docs"), "components/spinner.mdx": () => import("../content/docs/components/spinner.mdx?collection=docs"), "components/status-bar.mdx": () => import("../content/docs/components/status-bar.mdx?collection=docs"), "components/tab-bar.mdx": () => import("../content/docs/components/tab-bar.mdx?collection=docs"), "components/table.mdx": () => import("../content/docs/components/table.mdx?collection=docs"), "components/terminal-window.mdx": () => import("../content/docs/components/terminal-window.mdx?collection=docs"), "components/text-input.mdx": () => import("../content/docs/components/text-input.mdx?collection=docs"), "guides/nextjs.mdx": () => import("../content/docs/guides/nextjs.mdx?collection=docs"), "guides/testing.mdx": () => import("../content/docs/guides/testing.mdx?collection=docs"), "guides/theming.mdx": () => import("../content/docs/guides/theming.mdx?collection=docs"), "guides/vite.mdx": () => import("../content/docs/guides/vite.mdx?collection=docs"), }),
};
export default browserCollections;